[package]
name = "app_ui"
version.workspace = true
edition.workspace = true

[dependencies]
repose-ui.workspace = true
repose-core.workspace = true
repose-material.workspace = true
repose-navigation.workspace = true
domain = { path = "../domain" }
crossbeam-channel.workspace = true
serde.workspace = true
rfd.workspace = true
